FROM ubuntu

RUN apt-get update && apt-get install -y curl gettext-base build-essential
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN mv kubectl /usr/bin
RUN chmod +x /usr/bin/kubectl
